### ISSUE TITLE
Need for extra filters for disk discovery in cloud environments (GCP)

### ISSUE THREAD

**Issue by leelavg** [alauda/topolvm-operator#30]
hello,

- Thanks for all the efforts for creating and maintaining this project, can you pls help me with below issues if possible?
- Deployed Topolvm operator on OCP 4.x with required feature gates opened on GCP via Operatorhub (v2.0.0)
- Below is the manifest file for `TopolvmCluster`
``` yaml
apiVersion: topolvm.cybozu.com/v2
kind: TopolvmCluster
metadata:
  name: topolvmcluster-sample
  namespace: topolvm-system
spec:
  topolvmVersion: "alaudapublic/topolvm:2.0.0"
  storage:
    useAllNodes: true
    useAllDevices: true
    useLoop: true
    volumeGroupName: test
    className: hdd
```
- Consider each node (3 masters + 3 workers) has below disks
```
-> oc debug nodes/xxx-worker-a-zrtzc.c.xxx -- lsblk
Starting pod/xxx-worker-a-zrtzc.c.xxx-debug ...
To use host binaries, run `chroot /host`
NAME   MAJ:MIN RM   SIZE RO TYPE MOUNTPOINT
sda      8:0    0   128G  0 disk 
|-sda1   8:1    0     1M  0 part 
|-sda2   8:2    0   127M  0 part 
|-sda3   8:3    0   384M  0 part /host/boot
`-sda4   8:4    0 127.5G  0 part /host/sysroot
sdb      8:16   0    10G  0 disk 
sdc      8:32   0    10G  0 disk 

Removing debug pod ...
```
- Ideally `/dev/sd{b,c}` should be considered for vgcreation and partitions in `/dev/sda` should be excluded
- However, below is the result of data stored under `devices` in lvmdconfig-xxx
``` json
[
  {
    "name": "sda1",
    "parent": "sda",
    "hasChildren": false,
    "devLinks": "/dev/disk/by-id/google-persistent-disk-0-part1 /dev/disk/by-partuuid/2c82abb4-778a-41b5-8e2b-1576bd2b0b8f /dev/disk/by-path/pci-0000:00:03.0-scsi-0:0:1:0-part1 /dev/disk/by-id/scsi-0Google_PersistentDisk_persistent-disk-0-part1 /dev/disk/by-partlabel/BIOS-BOOT",
    "size": 1048576,
    "uuid": "",
    "serial": "0Google_PersistentDisk_persistent-disk-0",
    "type": "part",
    "rotational": false,
    "readOnly": false,
    "Partitions": null,
    "filesystem": "",
    "vendor": "Google",
    "model": "PersistentDisk",
    "wwn": "",
    "wwnVendorExtension": "",
    "empty": false,
    "real-path": "/dev/sda1",
    "kernel-name": "sda1"
  }
]
```

Issues:
1. Operator picked up `sda1` for vg creation and failed due to less space (1MB), so we might need a filter for minimum size of disk to consider for vg?
2. `sda1` shouldn't be picked up in the first place as it is of type `BIOS-BOOT` and should be skipped, it might contain MBR?
3. Result of issue1, when vgcreation failed, operator didn't walk through other healthy devices `sd{b,c}` as every reconcile will anyways fail, probably it's better to create vg on those?
