### ISSUE TITLE
[Question] Multiple deviceclasses with same node name

### ISSUE THREAD

**Issue by leelavg** [alauda/topolvm-operator#61]
- Does current CR supports before cluster manifest, I think it'll fail in creating a config map due to name clash 🤔 
- One usecase would be different `className` type (`hdd` vs `ssd`)

``` yaml
# ...
    deviceClasses:
      - nodeName: node-0
        classes:
          - volumeGroup: test-master-0
            className: hdd
            default: true
            devices: 
              - name: "/dev/sdc"
                type: "disk"
              - name: "/dev/sdd"
                type: "disk"
      - nodeName: node-0
        classes:
          - volumeGroup: test-master-1
            className: ssd
            devices: 
              - name: "/dev/sde"
                type: "disk"
              - name: "/dev/sdf"
                type: "disk"
```

**Comment by leelavg** [comment]
- In-correct, manual already mentions the use case. Pardon the inconvenience.

**Comment by little-guy-lxr** [comment]
> * Does current CR supports before cluster manifest, I think it'll fail in creating a config map due to name clash 🤔
> * One usecase would be different `className` type (`hdd` vs `ssd`)
> 
> ```yaml
> # ...
>     deviceClasses:
>       - nodeName: node-0
>         classes:
>           - volumeGroup: test-master-0
>             className: hdd
>             default: true
>             devices: 
>               - name: "/dev/sdc"
>                 type: "disk"
>               - name: "/dev/sdd"
>                 type: "disk"
>       - nodeName: node-0
>         classes:
>           - volumeGroup: test-master-1
>             className: ssd
>             devices: 
>               - name: "/dev/sde"
>                 type: "disk"
>               - name: "/dev/sdf"
>                 type: "disk"
> ```
not support the format that you provided, you shoud modify to this:
```yaml
    deviceClasses:
      - nodeName: node-0
        classes:
          - volumeGroup: test-master-0
            className: hdd
            default: true
            devices: 
              - name: "/dev/sdc"
                type: "disk"
              - name: "/dev/sdd"
                type: "disk"
          - volumeGroup: test-master-1
            className: ssd
            devices: 
              - name: "/dev/sde"
                type: "disk"
              - name: "/dev/sdf"
                type: "disk"
```
