### ISSUE TITLE
[Question] Support for devices at storage level with no deviceclasses

### ISSUE THREAD

**Issue by leelavg** [alauda/topolvm-operator#73]
- I can think of a usecase for below CR, like, specific devices from specific nodes but no `deviceClass` from the nodes. Just checking whether it's intentional not to support below type or is it any bug?
``` yaml
---                                                                                                                                                                                          
apiVersion: topolvm.cybozu.com/v2                                                                                                                                                            
kind: TopolvmCluster                                                                                                                                                                         
metadata:                                                                                                                                                                                    
  name: sample-cr                                                                                                                                                                            
  namespace: topolvm-system                                                                                                                                                                  
spec:                                                                                                                                                                                        
  topolvmVersion: "quay.io/topolvm/topolvm-with-sidecar:0.10.2"                                                                                                                              
  storage:                                                                                                                                                                                   
    # single device class with nodename, devices at storage level                                                                                                                            
    useAllNodes: false                                                                                                                                                                       
    useAllDevices: false                                                                                                                                                                     
    useLoop: false                                                                                                                                                                           
    devices:                                                                                                                                                                                 
      - name: "/dev/nvme1n1"                                                                                                                                                                 
        type: "disk"                                                                                                                                                                         
      - name: "/dev/nvme2n1"                                                                                                                                                                 
        type: "disk"                                                                                                                                                                         
      - name: "/dev/nvme3n1"                                                                                                                                                                 
        type: "disk"                                                                                                                                                                         
      - name: "/dev/nvme4n1"
        type: "disk"                           
    deviceClasses:                             
      - nodeName: "ip-10-0-146-72.ap-south-1.compute.internal"
        classes:                               
          - volumeGroup: test-master
            className: hdd
            default: true
```
